title: Rachel Cochrane
email: rcoch@roe.ac.uk
description: > # this means to ignore newlines until "baseurl:"
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://rcoch.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Rachel Cochrane # add your name
author-pic: boat_photo.jpg
about-author: I am a John Harvard Distinguished Science fellow based at the Harvard-Smithsonian Center for Astrophysics. I received my PhD in 2019 from the University of Edinburgh.


My primary interest is the evolution of galaxies over cosmic time, in particular the fuelling and quenching of star formation at intermediate redshifts (z~1-3). I work on both large scales, probing galaxy environments via clustering, and small scales, studying the spatially-resolved properties of individual galaxies. I use data from telescopes spanning many wavelengths, from the ultraviolet with the Hubble Space Telescope to radio wavelengths with LOFAR. My research blends these observations with cosmological hydrodynamical simulations such as EAGLE and FIRE. 

# Contact links
email: rcoch@roe.ac.uk
#phone: Add your Phone number
website: rcoch.github.io/about/ 
#linkedin: Add your Linkedin handle
github: rcoch # Add your Github handle
twitter: '@rachelkcochrane' # Add your Twitter handle
#facebook: Add your Facebook handle
#instagram:  Add your Instagram handle
#pinterest:  Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 3
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
