title: Rachel Cochrane
email: rcoch@roe.ac.uk
description: > # this means to ignore newlines until "baseurl:"
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rcoch.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Rachel Cochrane # add your name
author-pic: boat_photo.jpg
about-author: Astrophysics PhD graduate, incoming postdoctoral fellow at Harvard ITC.

# Contact links
email: rcoch@roe.ac.uk
#phone: Add your Phone number
#website: Add your website, do not add http://
#linkedin: Add your Linkedin handle
github: rcoch # Add your Github handle
twitter: '@rachelkcochrane' # Add your Twitter handle
#facebook: Add your Facebook handle
#instagram:  Add your Instagram handle
#pinterest:  Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 2
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
